spring:
  application:
    name: user
  security:
    oauth2:
      client:
        registration:
          keycloak:
            serverUrl: http://localhost:8181
            realm: vinylSound
            client-id: user-client
            client-secret: E5KuRVyVdD4xGGV3kacsUKsACcyQr39h