version: "1"

services:
  db:
    container_name: db
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: vinylSound
      MYSQL_DATABASE: vinylSound
      MYSQL_USER: user-vinylSound
      MYSQL_PASSWORD: pass-vinylSound
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: "true"
    healthcheck:
      test: "mysql -uuser-vinylSound -ppass-vinylSound -e 'SELECT 1;'"
      interval: 30s
      retries: 5
    volumes:
      - mysql_data_volume:/var/lib/mysql
    networks:
      - vinylSound

volumes:
  mysql_data_volume:
networks:
  vinylSound:
    driver: bridge