version: "1"

services:
  db:
    container_name: db
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: vinylSound
      MYSQL_DATABASE: vinylSound
      MYSQL_USER: user-vinylSound
      MYSQL_PASSWORD: pass-vinylSound
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: "true"
    healthcheck:
      test: "mysql -uuser-vinylSound -ppass-vinylSound -e 'SELECT 1;'"
      interval: 30s
      retries: 5
    volumes:
      - mysql_data_volume:/var/lib/mysql
    networks:
      - vinylSound

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "keycloak" ]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_volume:/var/lib/postgres
    networks:
      - keycloak

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev","--import-realm"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - postgres
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: db
      DB_DATABASE: vinylSoundKeycloak
      DB_PORT: 5433
      DB_USER: user-vinylSound
      DB_PASSWORD: pass-vinylSound
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181
    volumes:
      - ./auth/import/:/opt/keycloak/data/import
    networks:
      - keycloak

volumes:
  mysql_data_volume:
  postgres_data_volume:
networks:
  vinylSound:
    driver: bridge
  keycloak:
    driver: bridge