version: "1"

services:
  catalog-db:
    container_name: catalog-db
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: vinylSound
      MYSQL_DATABASE: catalog
      MYSQL_USER: user-vinylSound
      MYSQL_PASSWORD: pass-vinylSound
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: "true"
    healthcheck:
      test: "mysql -uuser-vinylSound -ppass-vinylSound -e 'SELECT 1;'"
      interval: 30s
      retries: 5
    volumes:
      - catalog_data_volume:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - vinylSound

  order-db:
    container_name: order-db
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: vinylSound
      MYSQL_DATABASE: order
      MYSQL_USER: user-vinylSound
      MYSQL_PASSWORD: pass-vinylSound
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: "true"
    healthcheck:
      test: "mysql -uuser-vinylSound -ppass-vinylSound -e 'SELECT 1;'"
      interval: 30s
      retries: 5
    volumes:
      - order_data_volume:/var/lib/mysql
    networks:
      - vinylSound

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "keycloak" ]
    environment:
      POSTGRES_DB: vinylSoundKeycloak
      POSTGRES_USER: user-vinylSound
      POSTGRES_PASSWORD: pass-vinylSound
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    networks:
      - keycloak

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev","--import-realm"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - postgres
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: vinylSoundKeycloak
      DB_PORT: 5432
      DB_USER: user-vinylSound
      DB_PASSWORD: pass-vinylSound
      KEYCLOAK_ADMIN: vinylsoundinformation@gmail.com
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181
    volumes:
      - ./auth/import/:/opt/keycloak/data/import
    networks:
      - keycloak

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 15672
      - 5672
    volumes:
      - rabbitmq_data_volume:/var/lib/rabbitmq

volumes:
  catalog_data_volume:
  order_data_volume:
  postgres_data_volume:
  rabbitmq_data_volume:
networks:
  vinylSound:
    driver: bridge
  keycloak:
    driver: bridge