version: "1"

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev","--import-realm"]
    ports:
      - 8181:8181
    expose:
      - 8181
    environment:
      KEYCLOAK_ADMIN: vinylsoundinformation@gmail.com
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181
    volumes:
      - ./auth/import/:/opt/keycloak/data/import

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 15672
      - 5672
    volumes:
      - rabbitmq_data_volume:/var/lib/rabbitmq
volumes:
  rabbitmq_data_volume:
